mcp:
  host: 0.0.0.0
  port: 8000

model:
  name: "qwen3-coder-30b"
  key: ""
  url: "http://10.66.12.247:30001/v1"
  # name: "xiyan-32b"
  # key: ""
  # url: "http://10.66.12.247:30002/v1"

database:
  dialect: "postgresql"
  host: "10.66.12.247"
  port: 5432
  user: "dev"
  password: "51World@123"
  database: "djy"